### ISSUE TITLE
Keine DejaVu auf Windows

### ISSUE THREAD

**Issue by ccoenen** [LongHairedHacker/fedidwgugl-generator#1]
![grafik](https://user-images.githubusercontent.com/124909/27512060-40130134-5935-11e7-95e8-9f8a6f41f85c.png)

(Windows 10, Firefox)

**Comment by LongHairedHacker** [comment]
Welche Firefox Version den genau?

Ich benutze diese neumodische [FontFace API](https://developer.mozilla.org/en-US/docs/Web/API/FontFace) um den nachzuladen.
Das war als Workaround zu dem [Problem](https://stackoverflow.com/questions/2756575/drawing-text-to-canvas-with-font-face-does-not-work-at-the-first-time) gedacht, dass das javascript schon läuft und der Browser noch am Fonts laden ist.
Ein div ohne Inhalt mit dem Font gesetzt reicht nämlich irgendwie nicht mehr um das Laden zu erzwingen.

Irgendwelche Vorschläge?

**Comment by LongHairedHacker** [comment]
Hab mal was mit nem div und einem &nbsp; gefrickelt um das Laden zu forcieren und den FontAPI Teil rausgenommen.
Außerdem noch ein paar mehr Fontformate für den Fall, dass der  Browser kein WOFF mag.

Sag mal Bescheid ob das was bringt.

**Comment by ccoenen** [comment]
![grafik](https://user-images.githubusercontent.com/124909/27512738-98099464-594b-11e7-8810-330514b8e0fb.png)

Und: Firefox 54, um deine Rückfrage zu beantworten :)
